# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf27e83143565f510ddd0022fde095840b99cc9405094db2b03f1f05d149f3a5719963c01dc2e5fedb30dea3aad9fbfe12c6cfb5fc9b78d606f91ada4fac81c

test:
  secret_key_base: 18ec5a50f57acfb65abd739a521ea733d5edd0b6e6f879a06bf4d8ace797ad215f6ba79c85b63a30f84cc2b0f958ea4affa5c17294e947ecfdf81ddf4e8a5398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
